### ISSUE TITLE
"EOF before complete http11 header" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [algesten/hreq#46]
On some websites, e.g. http://athenahealth.com, hreq fails with the following error:

> EOF before complete http11 header

Firefox and curl work fine. Reqwest also fails.

292 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/src/main.rs) and [this `Cargo.lock`](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/hreq-smoke-test/Cargo.lock). Test tool output for all occurrences: [hreq-eof-before-header.tar.gz](https://github.com/algesten/hreq/files/6242288/hreq-eof-before-header.tar.gz)

**Comment by algesten** [comment]
This was due to three cases.

1. Some sites on redirect, just close the connection before sending the last `\r\n\r\n` (curl handles this).
2. Some sites do not use `<cr>`, just `\n\n` to end the header (curl handles this).
3. Some sites sends no http response headers, not even the HTTP status line (curl handles this).

hreq now handles 1 and 2. However 3 is a bit too broken to be interesting.

Here is a list of sites that still fail with a variant of "EOF before complete header" in hreq, but succeeds in curl.

```
http://123c.vn
http://cryptoarabe.com
http://ctbdigital.com.br
http://mac-lyon.com
http://mba-lyon.fr
http://smtpcorp.com
http://tfd.org.tw
http://uni-sb.de
http://verifalia.com
```
